version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run:
          name: Eslint Install
          command: npm install --save-dev eslint eslint-config-strongloop
      - run:
          name: Eslint Pretest
          command: npm run pretest
      - run:
          name: Build App
          command: ng build
workflows:
    build-and-test:
      jobs:
        - build-and-test